<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6"/>
        <!-- Audit Trails related related packages -->
        <PackageReference Include="EntityFrameworkCore.CreatedUpdatedDate" Version="8.0.0"/>
        <!-- Entity Framework Core related packages -->
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.5"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational.Design" Version="1.1.6"/>
        <!-- MySQL Entity Framework Core related packages -->
        <PackageReference Include="MySql.EntityFrameworkCore" Version="9.0.3"/>
        <!-- Naming convention conversion related packages -->
        <PackageReference Include="Humanizer" Version="2.14.1"/>
        <!-- Swagger related packages -->
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.2"/>
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.2"/>
        <!-- JWT Authentication related packages -->
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0-preview.5.24306.11" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
        <!-- Password hashing -->
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="HealthyLife\application\" />
      <Folder Include="HealthyLife\domain\model\" />
      <Folder Include="HealthyLife\infrastructure\" />
      <Folder Include="HealthyLife\interfaces\" />
    </ItemGroup>

</Project>
